### ISSUE TITLE
Nieuwe gebruiker ziet oude cases niet

### ISSUE THREAD

**Issue by FransClements** [pietk/werkwel#12]
Dit is volgens mij een bug. 
Een nieuwe gebruiker krijgt geen inzicht van de cases die al door anderen zijn ingevoerd.

**Comment by pietk** [comment]
Duplicate met #4

**Comment by FransClements** [comment]
Wow. Github werkt!
Op 7 mei 2015 23:45 schreef "pietk" <notifications@github.com>:

**Comment by thiscor** [comment]
Ja mooi hè? Die e-mail notificaties 😀
