### ISSUE TITLE
Acceptatie popup bij opvraag contact gegevens door client

### ISSUE THREAD

**Issue by FransClements** [pietk/werkwel#14]
Acceptatie van opvragen contact gegevens. Popup: Uw gegevens worden na akkoord aan de cliënt toegestuurd. Weet u het zeker?

Tzt zou er ook nog een optie bij kunnen. Kunt u mij ook uw gegevens toesturen?

**Comment by thiscor** [comment]
Ik denk een discussiepunt: Opvragen contactgegevens IMHO alleen mogelijk als bijde partijen tegelijktijdig wederzijds contactgegevens uitwisselen. Dus als persoon A aan B om zijn contactgegevens vraagt en B gaat akkoord dan krijg B daarvoor als dank ook de contactgegevens van A.  Dus alleen uitwisselen en 1 richtingsverkeer van contactgegevens moeten we uitsluiten.  Het lijkt mij ongewenst dat 1 partij anoniem blijft en de andere partij zijn contactgegevens moet prijsgeven.

**Comment by FransClements** [comment]
ja, alleen ik vergelijk het met winkelen. Ik ga schoenen kopen. De winkel (Tamalone contact) is bekend, maar men kent niet gelijk mijn naam. 
In Tamalone zijn mi de contacten de winkels, echter kan het contact zich in eerste instantie niet profileren, dan alleen door inhoudelijk in te gaan op de case. Ik als cliënt moet de mogelijkheid krijgen te weten welke winkel ik ingestapt ben (met welk contact ik interactie heb). 
Ook in een winkel wil ik nl. vaak mijn naam niet kwijt: men gaan mijn gegevens dan nl. gebruiken voor allerlei reclame en marketing doeleinden.

**Comment by FransClements** [comment]
In Github gereageerd. Krijgen jullie daar automatisch een mail van?
Of had ik zelfs in deze e-mail kunnen reageren?

Frans

Op 9 mei 2015 00:37 schreef thiscor <notifications@github.com>:

**Comment by thiscor** [comment]
Ja wij krijgen daarvan direct bericht per mail, je kunt ook reply doen op de mail, die komen automatisch als comment onder het ticket

**Comment by thiscor** [comment]
Idd werkgever mag als eerste zijn contact details prijsgeven, lijkt me goed, klant is koning :)
