### ISSUE TITLE
Als bod wordt gedaan wordt het scherm van de cliënt niet refreshed. 

### ISSUE THREAD

**Issue by FransClements** [pietk/werkwel#17]
Als expert en cliënt gelijktijdig in het scherm zijn en expert doet een bod, wordt het scherm van de cliënt niet refreshed met het bod.

**Comment by thiscor** [comment]
Ook controloren of anderen wijzigingen direct zichtbaar worden via event-service:
- Biedingen
- Acceptaties
- Akkoord voor tonen Contactgegevens
- Binnengekomen beoordelingen
- Chat berichten
- Etc...
