### ISSUE TITLE
Eenheid voor WerkWel transacties graag in Uren ipv Euros

### ISSUE THREAD

**Issue by FransClements** [pietk/werkwel#24]
Mag voor werkwel de eenheid omgezet worden in "uren". 

Suggestie, maak de eenheid gebruikers of app afhankelijk of zelfs case afhankelijk.

**Comment by FransClements** [comment]
Nav test 1 - Vrijdag 16 juni

Voor de WerkWel implementatie moet bij bieding moet Euro uren worden. 
![image](https://cloud.githubusercontent.com/assets/12268191/8157645/5791540e-1356-11e5-9d66-dce418519544.png)


Suggestie verandering tekst: 
Ik kan leveren in ... uren

**Comment by FransClements** [comment]
Svp een kleine wijziging. Andere suggestie: kan de eenheid als pull down worden weergegeven?
Dus Euro of Uren. 
Dit heeft dan wel consequenties voor de transacties.. Die moeten mi dan niet vermengd worden. 
En bij selectie van uren, pop-up tekst. Uren kunnen alleen uitgewisseld worden tussen werkzoekenden. 

Mi heeft dit nog wel even discussie nodig.

**Comment by FransClements** [comment]
Piet, oplossing is nog niet operationeel.

**Comment by FransClements** [comment]
1. Als een nieuwe case door cliënt wordt toegevoegd en daarna in het detail scherm wordt bijgewerkt, wordt de bijgewerkte case niet in het dashboard expert refreshed.
2. Ja, interactie push van scherm naar ander scherm werkt. 
3. bolletje wordt ook zichtbaar als alleen in het dashboard. Mi moet het bolletje pas weg als echt gereageerd is. Nu gaat het bolletje weg als het detail scherm is ingegaan. 
4. Ja, felicitas! Er komt een bolletje als gebruiker in het dashboard is en niets doet!
![image](https://cloud.githubusercontent.com/assets/12268191/8281763/79f93d8c-18eb-11e5-8e2c-85943adaf05f.png)


Alleen 1 en 3 hebben mi dus aandacht nodig.

**Comment by pietk** [comment]
Dit issue gaat over uren ipv euro's. Graag test informatie toevoegen bij
het juiste issue.
Close #24

2015-06-22 14:38 GMT+02:00 Frans Clements <notifications@github.com>:
