### ISSUE TITLE
Case verdwijnt voor andere experts

### ISSUE THREAD

**Issue by FransClements** [pietk/werkwel#27]
Als één expert reageert op een case, kunnen andere experts niet meer reageren. De case verdwijnt dan voor de andere experts. 

Suggestie oplossing. Geef een default van 10 reacties per case. Deze kan de cliënt overschrijven.

**Comment by thiscor** [comment]
Lijkt mij dat meerdere experts onafhankelijk van elkaar mogen reageren op 1 en dezelfde case. In een eigen unieke 'discusion thread'

**Comment by FransClements** [comment]
Ja, mee eens, waarbij de client aangeeft hoeveel reactie hij maximaal wil hebben. 
Dit was ook een suggestie in de meeting met jongerenvoorjongeren. 
Om te voorkomen dat je "honderden" reacties gaat krijgen. 

Persoonlijk ben ik daar niet zo bang voor. Ook in marktplaats kun je op een advertentie vele reacties krijgen. Maar mijn ervaring is dat dat meevalt.

**Comment by tvlastuin** [comment]
Dus: Ja, mee eens, waarbij de client aangeeft hoeveel reactie hij maximaal wil hebben.

**Comment by pietk** [comment]
Ik kan dit probleem niet reproduceren. Als een expert heeft gereageerd, heeft een andere expert de case nog steeds in de lijst ( wel in kolom 1, voor hem is het nog een  nieuwe case  )

**Comment by FransClements** [comment]
![image](https://cloud.githubusercontent.com/assets/12268191/7913866/5c050abe-0873-11e5-9c8b-68b87823b149.png)


Piet, inglogd met privefransclements@gmail.com
Ik krijg nu ook de cases niet meer te zien.

**Comment by pietk** [comment]
waarschijnlijk een javascript error.
Kan je met <Ctrl><Shift>J het debug console openen en als de error zichtbaar is nogmaals een screenshot maken?

**Comment by FransClements** [comment]
Het lukt me nu ook niet meer en het schermpje `uw bieding is geaccepteerd` verschijnt. 
Gefeliciteerd!
