### ISSUE TITLE
Vernieuwen

### ISSUE THREAD

**Issue by FransClements** [pietk/werkwel#28]
Kan de vernieuwen button toegevoegd worden?
En in het detail scherm een link naar de instellingen?

**Comment by FransClements** [comment]
In plaats daarvan moeten veranderingen direct zichtbaar worden

**Comment by thiscor** [comment]
Dit issue wordt al opgepakt in #17

**Comment by FransClements** [comment]
Vernieuwen gebeurd niet als ik een nieuwe case aanmaak. Vraag is of scherm refresh wel bij aanmaken nieuwe cases moet.

**Comment by FransClements** [comment]
Interactie refresh = OK

Bieden doet hij het niet. Refresh door F5

**Comment by FransClements** [comment]
Na acceptatie bod refreshed het scherm (cliënt scherm) waarin het bod is gedaan. Moet dat?!

Ook het expert scherm moet met F5 refreshed worden.
