### ISSUE TITLE
Eerste scherm blijft zichtbaar

### ISSUE THREAD

**Issue by FransWClements** [pietk/werkwel#3]
Zie e-mail

Johan, op een gegeven moment, als niet uitgelogd wordt krijg je dit scherm.
Is het niet beter dat de gebruiker in het dashboard blijft?

![image](https://cloud.githubusercontent.com/assets/12097551/7316715/a314af80-ea79-11e4-9540-f2cef8397d63.png)

**Comment by pietk** [comment]
Fixed by 4f8cd13517063ca93c73f1ee8c8f2ff3e600ed75
