### ISSUE TITLE
Aanmelden bij Google Apps als non-profit met werkwel.nl domein 

### ISSUE THREAD

**Issue by thiscor** [pietk/werkwel#30]
Taken:
- Registreren bij Google Apps voor non-profit organisaties via TechSoup account
- wekwel.nl domain verifieren en koppelen aan GoogleApps Engine en werkwel applicatie
- SSL Certificaat aanvragen bij TransIP en uploaden naar GoogleApps

**Comment by thiscor** [comment]
Done. Subdomein heet nu ik.werkwel.nl dus iedereen kan nu testen met http://ik.werkwel.nl

**Comment by FransClements** [comment]
https://ik.werkwel.nl/cases.html in beide bars
