### ISSUE TITLE
cache van login

### ISSUE THREAD

**Issue by FransClements** [pietk/werkwel#36]
Elke keer moet ik m'n login opnieuw intoetsen. Ook als gewoon uitgelogd is en cache niet opgeschoond

![image](https://cloud.githubusercontent.com/assets/12268191/7860310/31541d4c-0548-11e5-9ee8-f31d15900ceb.png)

**Comment by thiscor** [comment]
Gebruik je niet toevallig een incognito browser window?


Johan Rosman

**Comment by thiscor** [comment]
Wat ook nog een mogelijkheid is dat je eerst inlogde via http://werkwel-test.appspot.com en nu met het nieuwe domein http://ik.werkwel.nl 

Dan klopt je bewering @fwclements en bij een ander domein horen weer nieuwe Cookies. Maar dat Probleem is eenmalig

Ik sluit het ticket als niet reproduceerbaar.

**Comment by FransClements** [comment]
Ach dat is het.
Op 28 mei 2015 19:19 schreef "thiscor" <notifications@github.com>:

**Comment by FransClements** [comment]
Klopt.
Frans

Op 29 mei 2015 00:23 schreef thiscor <notifications@github.com>:

> Wat ook nog een mogelijkheid is dat je eerst inlogde via
> http://werkwel-test.appspot.com en nu met het nieuwe domein
> http://ik.werkwel.nl
>
> Dan klopt je bewering @fwclements <https://github.com/fwclements> en bij
> een ander domein horen weer nieuwe Cookies. Maar dat Probleem is eenmalig
>
> Ik sluit het ticket als niet reproduceerbaar.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pietk/werkwel/issues/36#issuecomment-106616892>.
>



-- 
Met vriendelijke groet,

Frans W. Clements
Partner WerkWel
Engelsestadweg 22
3772 TL, Barneveld
Tel.: 06 - 13  75 74 84
