### ISSUE TITLE
Test vrijdag 16 juni door T&F

### ISSUE THREAD

**Issue by FransClements** [pietk/werkwel#43]
1. Nieuwe case aangemaakt. Dashboard wordt niet gerefreshed met deze nieuwe case.
2. Label Testen ingegeven. Kan deze niet meer opvragen voor andere cases. 
3. Enter voor ingeven label werkt niet voor een domme gebruiker.
4. T reageert op case. Case gaat niet automatisch naar 2e kolom
5. F reageert op reactie T. De reactie wordt alleen met F5 zichtbaar. Reacties lijken niet meer gepushed te worden.
6. Bij bieding moet Euro uren worden.
7. Mooi dat er nu een message komt, er is een bod gedaan, echter kan het bod niet gelijk gepresenteerd worden in deze pop-up?
8. Buttun accepteer bod moet nu opvallen en op een andere plaats komen. Het bod moet in ieder geval met de button accepteer bod in de pop-up komen en in een e-mail alert (als uitgelogd is).
9. Bod geaccepteerd, svp geef de gegevens in de pop-up mee. Niet de boodschap om te refreshen. 
Accepteer of cancel zijn beide een refresh. 
10. F heeft het bod geaccepteerd. De case komt in kolom3, is OK. Echter er moet ook een status, uitroepteken oid worden gedisplayed. 
11. Transactie wordt niet goed weergegeven. In het saldo moeten alleen de leveringen opgeteld worden!
12.De case omschrijving moet in het transactie overzicht. 
13. Kan er naast een transactie overzicht ook een saldo overzicht gemaakt worden?
14. Pas in de levering moet er iets in het saldo gebeuren.
15. Kan in de levering een plaatje of document ingekopieerd worden?
16. Kan bij de levering ook een invoerveld toegevoegd worden voor de algemene voorwaarden?
17. Kunnen de subschermen als layer boven het dashboard komen. 
18. Suggestie:maak kolom 3: acties en kolom 4:archief. Want de case is nu niet meer zichtbaar en de actie kolom geeft aan wat er per case gedaan moet worden
19. In archief op regel klikken en dan doorklikken naar het detail scherm.
20. Voeg tekst toe boven contacten. Uw winkelstraat, het aantal reacties op uw case.
21. Bedoordelingen van contact. svp met button activeren in het contact.
22. T klikt op een case,dan verdwijnen de 1 en 2 bolletjes. Hij heeft echter niets gedaan.
23. klikken op blauwe bolletje (mooi zal wel voor nieuwe case zijn!) echter, na detail scherm is hij uit de lijst.
24. Vraag T.Komt er een filter functie :-)
25. Case "ik kan schilderen". F doet bod. T staat in dashboard. Er gebeurd bij T niets. Dus refresh werkt niet als de gebruiker in het dashboard staat. Ook moet in tegel zichtbaar worden dat er een bod is gedaan. Of bolletje met accepteer bod, oid.

**Comment by thiscor** [comment]
Graag opsplitsen in losse tickets...

**Comment by FransClements** [comment]
T/m 15 doorgevoerd.

**Comment by FransClements** [comment]
Done!
