### ISSUE TITLE
Kolom namen

### ISSUE THREAD

**Issue by FransClements** [pietk/werkwel#46]
Nav test 1 - vrijdag 12 juni

We worstelen nog steeds met de duidelijkheid van de kolommen en te nemen acties. 
A. Kan de kolomnaam leveren veranderd worden in " Neem actie"? In deze kolom komen dus alle acties van reageer t/m beoordelen. 
B. Kan de kolom beoordelen veranderd worden in Archief? In deze kolom komen dan ook de verwijderde cases. 
C. Kan de kolom naam " Vragen" veranderd worden in " Nieuwe vragen" ?

![image](https://cloud.githubusercontent.com/assets/12268191/8157345/6fb2a6d4-1354-11e5-8ea7-e28964d16154.png)

De " Neem actie" kolom is dan eigenlijk de inbox waarin alles cases komen waarop actie genomen moet worden. 
Persoonlijk twijfel ik nog over de naam van de tweede kolom. Moet onderzoeken geen Winkelen worden? Je creëert tenslotte een eigen winkelstraat.

**Comment by FransClements** [comment]
Na discussie toch weer een verandering van de kolom namen. Suggestie en ter discussie:

Namen:
Kolom 1: Vragen
Kolom 2: Reacties
Kolom 3: Uitvoeren (dit is dus leveren en beoordelen samen)
Kolom 4: Archief

**Comment by FransClements** [comment]
De kolom namen zijn veranderd, echter in archief worden nog de cases getoond die niet in het archief thuis horen zoals de cases waarvoor door cliënt nog de aktie beoordeling moet gedaan worden. 

![image](https://cloud.githubusercontent.com/assets/12268191/8494765/66a84950-2168-11e5-8e39-eb5d7dd8d9f2.png)

Zie bijvoorbeeld deze:
![image](https://cloud.githubusercontent.com/assets/12268191/8494796/9c19e436-2168-11e5-9b41-e4b64723d91a.png)

**Comment by pietk** [comment]
dit is een case die al een beoordeling heeft, die je als expert nog kunt bekijken

**Comment by FransClements** [comment]
Moet een case waarvan al een bieding is geaccepteerd, niet automatisch uit het dashboard van de andere experts gehaald worden?

Dus zodra cliënt een case accepteert, is geen interactie/bieding door andere experts meer mogelijk en de case ook niet zichtbaar. 

Misschien moet hier een melding bij op het moment dat cliënt accepteert. Pop-up met message: "Wilt u alleen doorgaan met deze bieding?"

**Comment by pietk** [comment]
We hebben speciaal ingebouwd dat meerdere biedingen geaccepteerd kunnen
worden, zodat ze bijvoorbeeld vergeleken kunnen worden.
Popup met vraag voor alleen deze bieding is nieuw feature, ik zou zeggen
voor een volgende release

Op 6 juli 2015 07:40 schreef Frans Clements <notifications@github.com>:

**Comment by FransClements** [comment]
OK
