### ISSUE TITLE
werkwel.noreply@gmail.com -> werkwel.noreply@werkwel.nl

### ISSUE THREAD

**Issue by thiscor** [pietk/werkwel#58]
We kunnen dit "noreply" e-mail adres nu in ons eigen domain hangen.

Taken: (30 minuten)
- Email box aanmaken  in admin console van Google Apps 
- werkwel.noreply@werkwel.nl regsitreren in GAE Development console bij appID "werkwel-test" van Goolgle Cloud Platform
- Verwijderen werkwel.noreply@gmail.com
- Javacode aanpassen.

**Comment by FransClements** [comment]
E-mail alert is mi een mijlpaal. Een enorme stap vooruit. Deze no-reply suggestie lijkt mij een goede implementatie van e-mail alert.

**Comment by pietk** [comment]
mail adres kan gewoon zijn: noreply@werkwel.nl
@thiscor kan jij die aanmaken ?

**Comment by thiscor** [comment]
Done

**Comment by pietk** [comment]
punt 2 is ook gedaan, alleen is er mail gestuurd om account te activeren.
Hoe kom ik in de mailbox ?

**Comment by pietk** [comment]
fixed

**Comment by FransClements** [comment]
Moet er wel een mailbox voor noreply aangemaakt worden?

**Comment by pietk** [comment]
Ja, anders kunnen we dit mailadres niet gebruiken in Google Apps om  mails
te versturen

Op 6 juli 2015 07:46 schreef Frans Clements <notifications@github.com>:

**Comment by thiscor** [comment]
Administratie e-mail adressen ivm overschakeling naar werkwel.nl domain

aangemaakt (4/7/2015)
noreply@werkwel.nl

verwijderd (per 7/72015):
tamalonexpert@gmail.com
tamaloneclient@gmail.com
tamalone.noreply@gmail.com
werkwel.noreply@gmail.com
