### ISSUE TITLE
Zoek & Filter

### ISSUE THREAD

**Issue by FransClements** [pietk/werkwel#6]
Zoekfunctie en filter inbouwen. Filter kan worden bewaard. Meerdere filters mogelijk. Filter start altijd met default filter = eigen vakgebied, expertise en groep.

**Comment by thiscor** [comment]
duplicate van #22

**Comment by FransClements** [comment]
Zie https://forum.werkhoezithet.nl/
Kunnen wij deze manier van filteren nabouwen?!
Dus ook filteren op labels (categorieën, al is wat mij betreft label of groep als term prima).
