### ISSUE TITLE
Test aanmelden nav gebruiker Michiel die het niet lukte

### ISSUE THREAD

**Issue by FransClements** [pietk/werkwel#61]
Stap 1: okay
![image](https://cloud.githubusercontent.com/assets/12268191/8349739/a1287ee6-1b1f-11e5-830c-1146a8e5e4d7.png)

Stap 2: okay
![image](https://cloud.githubusercontent.com/assets/12268191/8349748/be63829e-1b1f-11e5-835e-d3e47a469c51.png)

Stap 3: Kan de message iets opschuiven naar het midden van het scherm?
![image](https://cloud.githubusercontent.com/assets/12268191/8349767/ec273ee6-1b1f-11e5-9194-52db8b3b9ab4.png)

Stap 4: E-mail onvangen in inbox test1@werkwel.nl = okay
![image](https://cloud.githubusercontent.com/assets/12268191/8349777/12d32b2c-1b20-11e5-90af-6d7f62b213de.png)

Stap 4: invullen gegevens 
Vraag: 
A. kan de geselecteerde gebruikerstype ook aangevuld worden bij de instellingen?
B. Kan het Linkedin of facebook adres ook toegevoegd worden? Dit ter controle van de persoon. 

![image](https://cloud.githubusercontent.com/assets/12268191/8349827/65a656da-1b20-11e5-90d1-630c86641fdc.png)

Stap 5: Gegevens opslaan. Hier gaat het mis. Ik vlieg terug in het inlogscherm, nadat in een flits het dashboard was te zien. 
![image](https://cloud.githubusercontent.com/assets/12268191/8349866/c1f3cde6-1b20-11e5-97fb-4cc06439c549.png)

Stap 6: inloggen met test1@werkwel.nl inloggegevens
![image](https://cloud.githubusercontent.com/assets/12268191/8349893/f0b56e0a-1b20-11e5-9d65-679c00c38628.png)

Stap 7: inloggen met test1@werkwel.nl en passwd
![image](https://cloud.githubusercontent.com/assets/12268191/8349952/704e01c2-1b21-11e5-90ea-54feec914823.png)

Stap 8: nieuw wachtwoord opvragen
Vraag: kan de pop-up meer naar het midden?
![image](https://cloud.githubusercontent.com/assets/12268191/8349969/97daf308-1b21-11e5-82f1-8910558d86ec.png)

Stap 9: Activeren
Opmerking: de tekst in de mail is verborgen (?!). 
![image](https://cloud.githubusercontent.com/assets/12268191/8349999/e89041fe-1b21-11e5-97df-ee164a4df8f6.png)

Stap 10: uitklappen en activeren
Vraag: is de inlogcode de usernaam of het e-mail adres?

![Uploading image.png…]()

Conclusie: 
kan (zie stap 5) de gebruiker gelijk doorgeleid worden naar het dashboard met een pop-up van de instellingen?

Waar het mi voor de gebruiker mis gaat is de user naam. Ik ging ervan uit dat ik het e-mail adres als logincode moest invullen. Wat moet dit zijn?

Zal deze test nog een keer herhalen. Of Cor, kunnen we dit samen doen (e-mail adressen genoeg! :-)

**Comment by thiscor** [comment]
Opmerking;

Bij het testen met meerdere gebruikers accounts met 1 en dezelfde browser kunnen er problemen onstaan met de 'Cookies' (zie bestaand critical issue #2) Er kan nl nog een geldige cookie kan zijn voor een andere gebruiker. Dus bij voorkeur verschillende browsers naastelkaar gebruiken IE / FF / CHROME en voor elk account een andere browser gebruiken of met incognito browsers werken. Maar dan moet je telkens inloggen.

Antwoorden op de vragen:

A) Inlognaam is gelijk aan e-mail adres. (Er is dus geen aparte inlognaam)

B) Koppeling aan Facebook/Twitter/LinkedIn/Social-Media is een nieuwe requirement -> Nieuw apart Ticket

C) Plaatsing van dialoog met feedback melding is de standaard javascript alert() method. De browser bepaalt waar deze geplaatst wordt. In Internet explorer komt deze in het midden. De feedback zou ook als HTML page gegeven kunnen worden en niet als een javascript alert(). Dan kunnen we ook beter de layout beinvloeden. -> Nieuw apart ticket

D) Het terugflitsen naar inlog scherm na 'Opslaan' van gebruikers gegevens is 'on purpose'.  Je bent namelijk vanuit de activation e-mail rechtstreeks in dit scherm gekomen om je 'aanmelding' af te ronden.  Zodra dat gereed is zul je 'echt' moeten inloggen met het zojuist opgegeven password. Het flitsen van het scherm naar het dashboard is niet acceptabel en verwarrend. -> Nieuw apart ticket.

Als de nieuwe tickets ingevoerd zijn dan kan deze gesloten worden.

**Comment by thiscor** [comment]
Losse tickets aangemaakt

**Comment by FransClements** [comment]
Antwoorden op de vragen:

A) Inlognaam is gelijk aan e-mail adres. (Er is dus geen aparte inlognaam)
Frans: ik zou voor deze optie kiezen. Wel Naam behouden, maar dat is als men de gegevens opvraagt voor face to face contact. 

B) Koppeling aan Facebook/Twitter/LinkedIn/Social-Media is een nieuwe requirement -> Nieuw apart Ticket gemaakt #62
Frans: Moet ik dit uitwerken, of svp kan een voorbeeld gebruikt worden?

C) Plaatsing van dialoog met feedback melding is de standaard javascript alert() method. De browser bepaalt waar deze geplaatst wordt. In Internet explorer komt deze in het midden. De feedback zou ook als HTML page gegeven kunnen worden en niet als een javascript alert(). Dan kunnen we ook beter de layout beinvloeden. -> Nieuw apart ticket #63
Frans: okay

D) Het terugflitsen naar inlog scherm na 'Opslaan' van gebruikers gegevens is 'on purpose'. Je bent namelijk vanuit de activation e-mail rechtstreeks in dit scherm gekomen om je 'aanmelding' af te ronden. Zodra dat gereed is zul je 'echt' moeten inloggen met het zojuist opgegeven password. Het flitsen van het scherm naar het dashboard is niet acceptabel en verwarrend. -> Nieuw apart ticket #64

**Comment by FransClements** [comment]
Johan, ik moet je punt D laten zien. Het opnieuw moeten inloggen is mi prima, alleen je ziet in een flits het dashboard, dat is mi raar.

**Comment by thiscor** [comment]
Dat is ook precies wat ik ook in ticket #64 heb vermeld
