### ISSUE TITLE
2 keer dezelfde case geplaatst

### ISSUE THREAD

**Issue by MarianSloot** [pietk/werkwel#72]
bij het plaatsen van een case gebeurde na 1x klikken niet direct iets. Daarom nog een keer geklikt. Resultaat: 2 identieke cases zijn aangemaakt. Dit zou eigenlijk niet mogelijk moeten zijn.
Het is ook niet mogelijk om er een te verwijderen.

**Comment by pietk** [comment]
dit zou nu beter moeten gaan, graag opnieuw testen

**Comment by FransClements** [comment]
Mijn internet gaat te snel. Bij mij gaat hij in ieder geval nu goed. 

En wat ook goed gaat; als ik vanuit de detail pagina de tekst wijzig wordt het dashboard ook refreshed.
En: plaats is toegevoegd!

**Comment by MarianSloot** [comment]
Het gaat nu inderdaad goed. Ik heb het getest bij een nieuwe case. Wel drie keer op de knop 'plaats case' geklikt, en de case verscheen desondanks één keer.
