### ISSUE TITLE
Afzender alert en onderwerp

### ISSUE THREAD

**Issue by FransClements** [pietk/werkwel#73]
![image](https://cloud.githubusercontent.com/assets/12268191/8431190/105a7bcc-1f38-11e5-94e0-8dc310901d51.png)

De naam van de ontvanger wordt niet ingevuld?
Is dat omdat ik in een vergaarbak e-mail account zit?

**Comment by pietk** [comment]
Nee, dit komt omdat je naam niet ingevuld is bij je gebruikersinstellingen

2015-06-30 15:01 GMT+02:00 Frans Clements <notifications@github.com>:
