### ISSUE TITLE
Beoordeling kan niet opgeslagen worden

### ISSUE THREAD

**Issue by FransClements** [pietk/werkwel#81]
![image](https://cloud.githubusercontent.com/assets/12268191/8495435/e3ef233e-216d-11e5-91be-c23ee8d2900d.png)

De button opslaan ontbreekt. Ik zou de naam van de button "akkoord" noemen. 

Ook het Tamalone icoon staat er nog. Suggestie: zou ik voor de detail schermen, dus ook hier helemaal weglaten. 
![image](https://cloud.githubusercontent.com/assets/12268191/8495466/270aef54-216e-11e5-9d09-745ce361db89.png)

(mooi logo trouwens!)

**Comment by pietk** [comment]
Dit is de beoordeling zoals gegeven door de client, die kan de expert niet aanpassen

**Comment by FransClements** [comment]
sorry!
