### ISSUE TITLE
Dashboard - Status per case - alert

### ISSUE THREAD

**Issue by FransClements** [pietk/werkwel#9]
Deze aanvraag enhancement is mi een belangrijke. We hebben hierover veel discussie gehad. 
De vraag is: hoe wordt een gebruiker door een case heen getrokken?
Ipv dat hij zelf moet zoeken naar een volgende stap of gewoon vergeet een volgende stap te nemen. 

Als conclusie is duidelijk dat e-mail wordt gebruikt. Hoe kan de gebruiker ook als hij het gespreksvenster in Tamalone heeft verlaten toch een melding krijgen dat iemand heeft gereageerd?
En met een klik terug komen in dit gesprek. 
Maar als hij wel in het gesprekswindow is en actief reageert, moet natuurlijk geen e-mail worden gestuurd. 

Ook van de andere (te nemen) acties moet hij op de hoogte gebracht worden.

**Comment by FransClements** [comment]
Kan er ook in het interactie scherm een default vinkje komen? 
![image](https://cloud.githubusercontent.com/assets/12268191/7745658/487f787c-ffad-11e4-8e5b-bd8ab799c916.png)

Met de omschrijving alert. Default staat deze dus aangevinkt. Voor alle andere actiestransacties wordt dan direct een mail verstuurd.  Voor interactie alleen als het vinkje aanstaat. Deze alert zorgt er dus dat als de tegenpartij reageert er een e-mail naar "mij" wordt gestuurd.

**Comment by FransClements** [comment]
E-mail voor alert. Moet ik de ppt toesturen?

![image](https://cloud.githubusercontent.com/assets/12268191/7745863/817a9502-ffae-11e4-9a21-21587e5dee4b.png)

**Comment by FransClements** [comment]
de ! voor alert is een stap vooruit. Zeker omdat de alert aangeeft dat iets gedaan moet worden. Kan daarom de status tekst worden? 
En door erop te klikken direct naar het detail scherm en betreffende window gaan?

**Comment by thiscor** [comment]
Ik geef de voorkeur aan een rood icon met het aantal nieuwe ongelezen notificaties zoals je vaak bij andere software ziet:
![alerticon](https://cloud.githubusercontent.com/assets/11872412/7938576/94e3ba78-0946-11e5-9668-1a3778b9104c.png)

**Comment by FransClements** [comment]
Prima, als de gebruiker door te klikken dan maar begeleid wordt (mi activatie window van actie) met de volgende stap. oid.

**Comment by pietk** [comment]
Maar, met alleen een rood icon met een cijfer zie je geen verschil tussen de verschillende notificaties. Hoe zou je dat zichtbaar willen maken dan?

**Comment by FransClements** [comment]
Hey Piet! Ja mee eens. Door in het icoontje aan te geven wat de volgende stap is, of waar om gevraagd wordt?

Dus: Reageer, of bied, of accepteer bod, etc.
?

**Comment by tvlastuin** [comment]
Lijke me goed voorstel van Frans!

**Comment by thiscor** [comment]
Zo'n icoontje is te klein om daarin al aan te geven wat de volgende stap is.  Volgens mij zijn er de volgende (verschillende) notificaties:

- Nieuw chat bericht binnengekomen
- Er is een bieding gedaan
- Er is een acceptatie van bod
- Er is een contactverzoek
- Er zijn contactgegevens binnengekomen
- ... Ben ik er nog vergeten te noemen...

Als je daarvoor 5 verschillende iconen zou hebben dan wordt het onduidelijk.  Ik vind het wel belangrijk dat je direct kunt zien op de case (bijvoorbeeld met het cijfertje in het rode rondje dat er een 'x' aantal nieuwe 'ongelezen' notificaties zijn.  Als je er dan met de muis overheen hovert dan zou je een popup kunnen laten zien met details. Of als je er op klikt de case openen en de notifications bekijken.

Daarnaast zou ik het nog een mooie optie vinden als de gebruiken helemaal bovenin zijn scherm (bijvoorbeeld naast de 'Gebruikersnaam' naast de 'instellingen knop' nog een (rood) alert icon hebt met het totaal van alle binnengekomen alerts van ALLE openstaande cases.

**Comment by FransClements** [comment]
Tja, aan u. Als ik maar als domme gebruiker niet hoef na te denken, te zoeken, ed. en toch door het proces heen gehaald wordt. 

Zoals Google hangouts of whatsapp. Wisten jullie trouwens dat SMS vervangen/geïntegreerd kan worden met Google hangouts?!

**Comment by pietk** [comment]
email wordt gestuurd als gebruiker offline is

**Comment by FransClements** [comment]
Ga ik nog vandaag testen Piet!
Frans
Op 23 jun. 2015 20:05 schreef "pietk" <notifications@github.com>:

**Comment by FransClements** [comment]
Gefeliciteerd!

1. Nieuwe case ingegeven. Andere gebruiker (expert) krijgt gelijk een alert!

Op of aanmerking of fout:
